In [2]:
import numpy as np
x = np.array([-1.0, 1.0, 2.0])
x

array([-1.,  1.,  2.])

In [3]:
y = x > 0

In [4]:
y

array([False,  True,  True], dtype=bool)

In [5]:
y = y.astype(np.int)
y

array([0, 1, 1])

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [7]:
x = np.array([-1.0, 1.0, 2.0])
sigmoid(x)

array([ 0.26894142,  0.73105858,  0.88079708])

In [8]:
A = np.array([1, 2, 3, 4])
A

array([1, 2, 3, 4])

In [9]:
np.ndim(A)

1

In [10]:
A.shape

(4,)

In [11]:
A.shape[0]

4

In [12]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.ndim(B)

2

In [14]:
B.shape

(3, 2)

In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [16]:
A.shape

(2, 2)

In [17]:
B.shape

(2, 2)

In [18]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [19]:
A @ B

array([[19, 22],
       [43, 50]])

In [20]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
a@b

14

In [21]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A.shape

(3, 2)

In [22]:
B = np.array([7, 8])
B.shape

(2,)

In [23]:
A @ B

array([23, 53, 83])

In [24]:
np.dot(A, B)

array([23, 53, 83])

In [25]:
A = np.array([[1, 2, 3], [1, 2, 3]])

In [27]:
A = np.array([[1, 2], [3, 4], [5, 6]])

In [28]:
A @ B

array([23, 53, 83])

In [29]:
X = np.array([1, 2])
X.shape

(2,)

In [30]:
W = np.array([[1, 3, 5], [2, 4, 6]])
W.shape

(2, 3)

In [31]:
Y = X @ W

In [32]:
Y

array([ 5, 11, 17])

In [33]:
print(Y)

[ 5 11 17]


In [2]:
import numpy as np
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])
A1 = (X @ W1) + B1

In [3]:
A1

array([ 0.3,  0.7,  1.1])

In [6]:
sigmoid

<function __main__.sigmoid>

In [7]:
Z1 = sigmoid(A1)

In [8]:
Z1

array([ 0.57444252,  0.66818777,  0.75026011])

In [10]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])
A2 = (Z1 @ W2) + B2

In [11]:
Z2 = sigmoid(A2)

In [12]:
Z2

array([ 0.62624937,  0.7710107 ])

In [13]:
def identity_function(x):
    return x

In [15]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])
A3 = (Z2 @ W3) + B3
Y = identity_function(A3)

In [16]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a)
sum_exp_a = np.sum(exp_a)
sum_exp_a

74.122154210163302

In [17]:
y = exp_a / sum_exp_a
y

array([ 0.01821127,  0.24519181,  0.73659691])

In [19]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    return exp_a / sum_exp_a

In [20]:
ls

ch03.ipynb          neuralnet_mnist_batch.py  sig_step_compare.py
mnist_show.py       relu.py                   sigmoid.py
neuralnet_mnist.py  sample_weight.pkl         step_function.py


In [21]:
pwd

'/home/yukirin/git/deep-learning-from-scratch/ch03'

In [22]:
python mnist.py

SyntaxError: invalid syntax (<ipython-input-22-11798591b720>, line 1)